// Database type definitions for Supabase
// This will be generated by Supabase CLI in the future

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          first_name: string;
          last_name: string;
          role: 'producer' | 'partner';
          phone?: string;
          bio?: string;
          location?: string;
          website?: string;
          avatar_url?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          first_name: string;
          last_name: string;
          role: 'producer' | 'partner';
          phone?: string;
          bio?: string;
          location?: string;
          website?: string;
          avatar_url?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          first_name?: string;
          last_name?: string;
          role?: 'producer' | 'partner';
          phone?: string;
          bio?: string;
          location?: string;
          website?: string;
          avatar_url?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      products: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string;
          category: 'vegetables' | 'fruits' | 'grains' | 'dairy' | 'meat' | 'herbs' | 'nuts' | 'other';
          price: number;
          unit: string;
          available_quantity: number;
          minimum_order?: number;
          harvest_date?: string;
          expiry_date?: string;
          location: string;
          organic: boolean;
          images: string[];
          status: 'active' | 'inactive' | 'sold_out';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          description: string;
          category: 'vegetables' | 'fruits' | 'grains' | 'dairy' | 'meat' | 'herbs' | 'nuts' | 'other';
          price: number;
          unit: string;
          available_quantity: number;
          minimum_order?: number;
          harvest_date?: string;
          expiry_date?: string;
          location: string;
          organic?: boolean;
          images: string[];
          status?: 'active' | 'inactive' | 'sold_out';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          description?: string;
          category?: 'vegetables' | 'fruits' | 'grains' | 'dairy' | 'meat' | 'herbs' | 'nuts' | 'other';
          price?: number;
          unit?: string;
          available_quantity?: number;
          minimum_order?: number;
          harvest_date?: string;
          expiry_date?: string;
          location?: string;
          organic?: boolean;
          images?: string[];
          status?: 'active' | 'inactive' | 'sold_out';
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          buyer_id: string;
          seller_id: string;
          product_id: string;
          quantity: number;
          price_per_unit: number;
          total_amount: number;
          delivery_address: string;
          delivery_date: string;
          notes?: string;
          status: 'pending' | 'confirmed' | 'shipped' | 'delivered' | 'cancelled';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          buyer_id: string;
          seller_id: string;
          product_id: string;
          quantity: number;
          price_per_unit: number;
          total_amount: number;
          delivery_address: string;
          delivery_date: string;
          notes?: string;
          status?: 'pending' | 'confirmed' | 'shipped' | 'delivered' | 'cancelled';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          buyer_id?: string;
          seller_id?: string;
          product_id?: string;
          quantity?: number;
          price_per_unit?: number;
          total_amount?: number;
          delivery_address?: string;
          delivery_date?: string;
          notes?: string;
          status?: 'pending' | 'confirmed' | 'shipped' | 'delivered' | 'cancelled';
          created_at?: string;
          updated_at?: string;
        };
      };
      chats: {
        Row: {
          id: string;
          participant_1: string;
          participant_2: string;
          last_message?: string;
          last_message_at?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          participant_1: string;
          participant_2: string;
          last_message?: string;
          last_message_at?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          participant_1?: string;
          participant_2?: string;
          last_message?: string;
          last_message_at?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          chat_id: string;
          sender_id: string;
          content: string;
          read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          chat_id: string;
          sender_id: string;
          content: string;
          read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          chat_id?: string;
          sender_id?: string;
          content?: string;
          read?: boolean;
          created_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      user_role: 'producer' | 'partner';
      product_category: 'vegetables' | 'fruits' | 'grains' | 'dairy' | 'meat' | 'herbs' | 'nuts' | 'other';
      product_status: 'active' | 'inactive' | 'sold_out';
      order_status: 'pending' | 'confirmed' | 'shipped' | 'delivered' | 'cancelled';
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

// Helper types
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];

// Specific table types
export type Profile = Tables<'profiles'>;
export type Product = Tables<'products'>;
export type Order = Tables<'orders'>;
export type Chat = Tables<'chats'>;
export type Message = Tables<'messages'>;

// Insert types
export type ProfileInsert = Database['public']['Tables']['profiles']['Insert'];
export type ProductInsert = Database['public']['Tables']['products']['Insert'];
export type OrderInsert = Database['public']['Tables']['orders']['Insert'];
export type ChatInsert = Database['public']['Tables']['chats']['Insert'];
export type MessageInsert = Database['public']['Tables']['messages']['Insert'];

// Update types
export type ProfileUpdate = Database['public']['Tables']['profiles']['Update'];
export type ProductUpdate = Database['public']['Tables']['products']['Update'];
export type OrderUpdate = Database['public']['Tables']['orders']['Update'];
export type ChatUpdate = Database['public']['Tables']['chats']['Update'];
export type MessageUpdate = Database['public']['Tables']['messages']['Update'];

// Enum types
export type UserRole = Enums<'user_role'>;
export type ProductCategory = Enums<'product_category'>;
export type ProductStatus = Enums<'product_status'>;
export type OrderStatus = Enums<'order_status'>;